version: '3.7'
volumes:
  sbam_prod_volume:

services:
  sbam_prod:
    build:
      context: .
      dockerfile: ./compose/prod/Dockerfile_prod
    command: /start.sh
    container_name: sbam_prod
    hostname: sbam_prod
    volumes:
      - .:/usr/src/sbam/
    ports:
      - 8080:8080
    env_file:
      - .env/prod/.env_app_prod
    depends_on:
      - db_prod
    restart: always

  db_prod:
    image: postgres:11
    container_name: db_prod
    hostname: db_prod
    volumes:
      - sbam_prod_volume:/var/lib/postgresql/data
    ports:
      - 5555:5432
    restart: always
    env_file:
      - .env/prod/.env_db_prod


