"""
Django settings for sbam project.

Generated by 'django-admin startproject' using Django 3.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/
import os

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Application definition

INSTALLED_APPS = [
    # model translation (If you want to use the admin integration must be put before django.contrib.admin)
    'modeltranslation',

    # django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # authentication
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # bootstrap theme
    'adminlte3',
    'adminlte3_theme',

    # form tools
    'widget_tweaks',
    'crispy_forms',

    # apps
    'sbam_app',

    # Tempus Dominus DateTimepicker
    'tempus_dominus',
]

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend",
)

SITE_ID = 1

LOGIN_URL = '/accounts/login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_URL = '/accounts/logout'
USER_MANAGEMENT_URL = '/users'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'sbam_app.middleware.LoginRequiredMiddleware',
]

LOGIN_EXEMPT_URLS = (
    r'admin/',
    r'accounts/'
)

ROOT_URLCONF = 'sbam.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_settings_export.settings_export',
            ],
        },
    },
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

WSGI_APPLICATION = 'sbam.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
#ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_SIGNUP_FORM_CLASS = 'sbam_app.forms.SignupForm'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = [
    'sbam_app/locale',
]

LANGUAGES = [
    ('el', _('Greek')),
    ('en', _('English')),
    ('it', _('Italian')),
    ('ro', _('Romanian')),
]


# Default lang of modeltranslation
MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = 'staticfiles'

# Project Specific User-Defined Variables

PROJECT_NAME = 'Energy Shield'
PROJECT_URL = 'https://energy-shield.eu/'
PROJECT_TWITTER = 'https://twitter.com/EnergyShield_'
PROJECT_LINKEDIN = 'https://www.linkedin.com/groups/8831159/'
PROJECT_EU_CONSENT = 'This project has received funding from the ' \
                     'European Union’s H2020 research and innovation ' \
                     'programme under the Grant Agreement No. 832907'

TOOL_NAME = 'Security Culture Tool'
TOOL_SHORT_NAME = 'SCT'

CONTACT_EMAIL = 'eshield@epu.ntua.gr'

SETTINGS_EXPORT = [
    'PROJECT_NAME',
    'PROJECT_URL',
    'PROJECT_TWITTER',
    'PROJECT_LINKEDIN',
    'PROJECT_EU_CONSENT',
    'TOOL_NAME',
    'TOOL_SHORT_NAME',
    'CONTACT_EMAIL'
]

# Tempus Dominus Settings
TEMPUS_DOMINUS_LOCALIZE = False
TEMPUS_DOMINUS_INCLUDE_ASSETS = False
