"""
Importing Django settings for sbam project,
automatically generated by 'django-admin startproject'
"""

from sbam.settings.base_settings import *

import environ

env = environ.Env()
# reading .env file
if 'DJANGO_DEVELOPMENT' in os.environ and env('DJANGO_DEVELOPMENT')==False:
    print('Starting Django using Production settings')
    env.read_env(env.str('ENV_PATH', '.env/prod/.env_app_prod'))
else:
    print('Starting Django using Development settings')
    env.read_env(env.str('ENV_PATH', '.env/dev/.env_app_dev'))

ADMINS = [x.split(" ") for x in env('ADMINS').split(",")]


# False if not in os.environ
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env('DJANGO_ALLOWED_HOSTS').split(" ")

# Raises django's ImproperlyConfigured exception if SECRET_KEY not in os.environ
SECRET_KEY = env('SECRET_KEY')

# Parse database connection url strings like psql://user:pass@127.0.0.1:8458/db
DATABASES = {
    # read os.environ['DATABASE_URL'] and raises ImproperlyConfigured exception if not found
    #'default': env.db(),
    # read os.environ['SQLITE_URL']
    #'extra': env.db('SQLITE_URL', default='sqlite:////tmp/my-tmp-sqlite.db')
    'default': {
        'ENGINE': env("SQL_ENGINE"),
        'NAME': env("SQL_DATABASE"),
        'USER': env("SQL_USER"),
        'PASSWORD': env("SQL_PASSWORD"),
        'HOST': env("SQL_HOST"),
        'PORT': env("SQL_PORT"),
    },
}

TIME_ZONE = env('TIME_ZONE')
LANGUAGE_CODE = env('LANGUAGE_CODE')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = env('EMAIL_USE_TLS')

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        'toolbar': [['Format'],
                    ['Bold', 'Italic', 'Undo', 'Redo'],
                    ['Link', 'Unlink'],
                    ['Image'],
                    ['SpecialChar'],
                    ['Source']],
        'tabSpaces': 4,
        'contentsCss': '/static/phishing_quiz/css/email-template.css',
    }
}

APPEND_SLASH = True

# STATIC_URL = '/static/'

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]
