# Generated by Django 3.0.5 on 2021-01-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0029_campaign_description'),
        ('email_simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(help_text='The assigment the simulation belongs', on_delete=django.db.models.deletion.PROTECT, to='sbam_app.TestAssignment', verbose_name='simulation_assignment')),
                ('email', models.ForeignKey(help_text='The email that is send for simulation', on_delete=django.db.models.deletion.PROTECT, to='email_simulation.SimEmail', verbose_name='simulation_email')),
            ],
        ),
    ]
