# Generated by Django 3.0.5 on 2021-01-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_simulation', '0002_emailassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='simemail',
            name='subject',
            field=models.CharField(default='', help_text='Simulation email subject', max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simemail',
            name='title',
            field=models.CharField(help_text='Simulation email title', max_length=100, verbose_name='title'),
        ),
    ]
