# Generated by Django 3.0.5 on 2021-01-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_simulation', '0003_auto_20210128_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simemail',
            name='subject',
            field=models.CharField(help_text='Simulation email subject', max_length=100, verbose_name='subject'),
        ),
    ]
