# Generated by Django 3.0.5 on 2021-01-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_simulation', '0004_auto_20210128_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailassignment',
            name='answer',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, verbose_name='active'),
        ),
    ]
