# Generated by Django 3.0.5 on 2020-11-17 17:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phishing_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishingemail',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
