# Generated by Django 3.0.5 on 2020-11-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishingemail',
            name='content',
            field=models.TextField(default='', help_text='Email content')
        ),
    ]
