# Generated by Django 3.0.5 on 2020-11-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing_quiz', '0002_auto_20201117_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingemail',
            name='is_phishing',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
