# Generated by Django 3.0.5 on 2020-11-24 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0028_auto_20201117_1931'),
        ('phishing_quiz', '0003_phishingemail_is_phishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingemail',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phishingemail',
            name='sender_display_name',
            field=models.CharField(default='', help_text="Sender's Name", max_length=100, verbose_name='sender_display_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phishingemail',
            name='sender_email',
            field=models.CharField(default='', help_text="Sender's Email", max_length=100, verbose_name='sender_email'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PhishingEmailAssignmentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.BooleanField()),
                ('assignment', models.ForeignKey(help_text='The assignment this answer belongs to', on_delete=django.db.models.deletion.PROTECT, to='sbam_app.TestAssignment')),
                ('email_id', models.ForeignKey(help_text='The email that is referred', on_delete=django.db.models.deletion.PROTECT, to='phishing_quiz.PhishingEmail', verbose_name='phishing_email')),
            ],
        ),
    ]
