# Generated by Django 3.0.5 on 2020-11-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phishing_quiz', '0004_auto_20201124_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phishingemailassignmentanswer',
            old_name='email_id',
            new_name='email',
        ),
    ]
