# Generated by Django 3.0.5 on 2020-11-24 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0028_auto_20201117_1931'),
        ('phishing_quiz', '0005_auto_20201124_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishingemailassignmentanswer',
            name='assignment',
            field=models.ForeignKey(help_text='The assignment this answer belongs to', on_delete=django.db.models.deletion.PROTECT, to='sbam_app.Assignment'),
        ),
    ]
