# Generated by Django 3.0.5 on 2020-11-25 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0028_auto_20201117_1931'),
        ('phishing_quiz', '0006_auto_20201124_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingEmailQuizScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Achieved score in phishing quiz', verbose_name='score')),
                ('assignment', models.ForeignKey(help_text='The assignment this answer belongs to', on_delete=django.db.models.deletion.PROTECT, to='sbam_app.Assignment')),
                ('quiz', models.ForeignKey(help_text='The email that is referred', on_delete=django.db.models.deletion.PROTECT, to='phishing_quiz.PhishingEmail', verbose_name='phishing_email')),
            ],
        ),
    ]
