# Generated by Django 3.0.5 on 2020-11-25 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phishing_quiz', '0007_phishingemailquizscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phishingemailquizscore',
            name='quiz',
        ),
    ]
