# Generated by Django 3.0.5 on 2020-12-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing_quiz', '0008_remove_phishingemailquizscore_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishingemail',
            name='content',
            field=models.TextField(default='', help_text='Email content'),
        ),
        migrations.AlterField(
            model_name='phishingemail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
