# Generated by Django 3.0.5 on 2021-02-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing_quiz', '0009_auto_20201201_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingemail',
            name='title',
            field=models.CharField(default='Test Title', help_text='Phishing email title', max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
    ]
