# Generated by Django 3.0.1 on 2019-12-24 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_title', models.CharField(max_length=50)),
                ('dimension_description', models.TextField(blank=True, default='')),
                ('dimension_level', models.CharField(choices=[('ORGANISATIONAL', 'Organisational'), ('INDIVIDUAL', 'Individual')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_title', models.CharField(max_length=50)),
                ('domain_description', models.TextField(blank=True, default='')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Dimension')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('question', models.ManyToManyField(related_name='choices', to='sbam_app.Question')),
            ],
        ),
    ]
