# Generated by Django 3.0.2 on 2020-01-15 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sbam_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleTextChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField(help_text='Choice text', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.DateField(blank=True, help_text="Person's data of birth", null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], help_text="Person's gender", max_length=10, null=True)),
                ('notes', models.CharField(blank=True, help_text='Notes', max_length=1000, null=True)),
                ('telephone', models.CharField(blank=True, help_text="Person's telephone", max_length=20, null=True)),
                ('user', models.OneToOneField(help_text='Django User ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.SmallIntegerField(blank=True, help_text="User's choice", null=True)),
                ('multipleChoice', models.ForeignKey(help_text="User's choice (from multiple)", on_delete=django.db.models.deletion.CASCADE, to='sbam_app.MultipleTextChoices')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='created',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Yes/No Question'), (1, 'Five Weight Scale'), (2, 'Percentage'), (3, 'Multiple Choice')], default=3, help_text='Question type'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='dimension_description',
            field=models.TextField(blank=True, default='', help_text='Dimension description'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='dimension_level',
            field=models.CharField(choices=[('ORGANISATIONAL', 'Organisational'), ('INDIVIDUAL', 'Individual')], help_text='Dimension level', max_length=20),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='dimension_title',
            field=models.CharField(help_text='Dimension title', max_length=50),
        ),
        migrations.AlterField(
            model_name='domain',
            name='dimension',
            field=models.ForeignKey(help_text='Dimension this domain belongs to', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Dimension'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_description',
            field=models.TextField(blank=True, default='', help_text='Domain description'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_title',
            field=models.CharField(help_text='Domain title', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='domain',
            field=models.ForeignKey(help_text='Domain this question belongs to', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Domain'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(help_text='Question text', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.AddField(
            model_name='userchoice',
            name='question',
            field=models.ForeignKey(help_text='Question this choice belongs to', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Question'),
        ),
        migrations.AddField(
            model_name='userchoice',
            name='user',
            field=models.ForeignKey(help_text='User this choice belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multipletextchoices',
            name='question',
            field=models.ForeignKey(help_text='Question this choice belongs to', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Question'),
        ),
    ]
