# Generated by Django 3.0.2 on 2020-01-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0002_auto_20200115_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='dimension_description',
            field=models.TextField(blank=True, default='', help_text='Dimension description', null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='dimension_level',
            field=models.SmallIntegerField(choices=[(0, 'Organisational'), (1, 'Individual')], help_text='Dimension level'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_description',
            field=models.TextField(blank=True, default='', help_text='Domain description', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], help_text="Person's gender", null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.CharField(blank=True, default='', help_text='Notes', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='telephone',
            field=models.CharField(blank=True, default='', help_text="Person's telephone", max_length=20, null=True),
        ),
    ]
