# Generated by Django 3.0.2 on 2020-01-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0003_auto_20200128_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='dateOfBirth',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, default='', help_text="Person's working address", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, help_text="Person's birth date", null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.CharField(blank=True, default='', help_text='Company this user belongs to', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.CharField(blank=True, default='', help_text='Department this user belongs to', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text="Person's display name", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='employee_id',
            field=models.IntegerField(blank=True, error_messages={'unique': 'A user with that employee id already exists.'}, help_text="Person's employee id", null=True, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Designates whether the user can have advanced business privileges within the tool.', verbose_name='manager status'),
        ),
        migrations.AddField(
            model_name='person',
            name='job_title',
            field=models.CharField(blank=True, default='', help_text="Person's job title", max_length=100, null=True),
        ),
    ]
