# Generated by Django 3.0.2 on 2020-02-03 11:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sbam_app', '0004_auto_20200128_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='UserProfile',
        ),
    ]
