# Generated by Django 3.0.2 on 2020-02-18 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sbam_app', '0005_auto_20200203_1320'),
        ('sbam_app', '0006_auto_20200305_1011'),

    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('OPEN', 0), ('COMPLETED', 1), ('CANCELLED', 2)], default=0, help_text='Status of an assignment if it is completed or not')),
                ('type', models.IntegerField(choices=[('QUESTIONNAIRE', 0), ('TEST', 1)], help_text='Type of assignment ')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_time', models.DateTimeField()),
                ('score', models.FloatField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.IntegerField(choices=[('FINISHED', 0), ('ACTIVE', 1), ('CANCELLED', 2)], default=1, help_text='Status of a Campaign')),
                ('user_owner', models.ForeignKey(help_text='The user who created the campaign', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.IntegerField(choices=[('ACTIVE', 1), ('INACTIVE', 0)], default=1, help_text='status of a questionnaire if it is used')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text="question's option text")),
                ('value', models.FloatField()),
                ('is_active', models.IntegerField(choices=[('ACTIVE', 1), ('INACTIVE', 0)], default=1, help_text='status of a questionnaire if it is used')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BL', 'boolean'), ('LT', 'likert_text'), ('LP', 'likert_percentage')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.IntegerField(choices=[('ACTIVE', 1), ('INACTIVE', 0)], default=1, help_text='status of a question if it is used')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Domain')),
            ],
        ),
        migrations.RemoveField(
            model_name='userchoice',
            name='multipleChoice',
        ),
        migrations.RemoveField(
            model_name='userchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userchoice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.IntegerField(choices=[('ACTIVE', 1), ('INACTIVE', 0)], default=1, help_text='status of a question if it is used'),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default='', help_text="question's text"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dimension',
            name='dimension_level',
            field=models.SmallIntegerField(choices=[('ORGANISTATIONAL', 0), ('INDIVIDUAL', 1)], help_text='Dimension level'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[('MALE', 0), ('FEMALE', 1)], help_text="Person's gender", null=True),
        ),
        migrations.CreateModel(
            name='QuestionnaireAssignment',
            fields=[
                ('assignment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sbam_app.Assignment')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Questionnaire')),
            ],
            bases=('sbam_app.assignment',),
        ),
        migrations.CreateModel(
            name='TestAssignment',
            fields=[
                ('assignment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sbam_app.Assignment')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Test')),
            ],
            bases=('sbam_app.assignment',),
        ),
        migrations.DeleteModel(
            name='MultipleTextChoices',
        ),
        migrations.DeleteModel(
            name='UserChoice',
        ),
        migrations.AddField(
            model_name='questionoption',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbam_app.QuestionType'),
        ),
        migrations.AddField(
            model_name='campaignquestionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Question'),
        ),
        migrations.AddField(
            model_name='campaignquestionanswer',
            name='question_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbam_app.QuestionOption'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Campaign'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sbam_app.QuestionType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Questionnaire'),
            preserve_default=False,
        ),
    ]
