# Generated by Django 3.0.2 on 2020-03-05 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sbam_app', '0005_auto_20200203_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimension',
            options={'verbose_name': 'dimension', 'verbose_name_plural': 'dimensions'},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'domain', 'verbose_name_plural': 'domains'},
        ),
        migrations.AlterModelOptions(
            name='multipletextchoices',
            options={'verbose_name': 'multiple text choice', 'verbose_name_plural': 'multiple text choices'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelOptions(
            name='userchoice',
            options={'verbose_name': 'user choice', 'verbose_name_plural': 'user choices'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AlterField(
            model_name='dimension',
            name='dimension_description',
            field=models.TextField(blank=True, default='', help_text='Dimension description', null=True, verbose_name='dimension description'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='dimension_level',
            field=models.SmallIntegerField(choices=[(0, 'Organisational'), (1, 'Individual')], help_text='Dimension level', verbose_name='dimension level'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='dimension_title',
            field=models.CharField(error_messages={'unique': 'A dimension with that title already exists.'}, help_text='Dimension title', max_length=50, unique=True, verbose_name='dimension title'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='dimension',
            field=models.ForeignKey(help_text='Dimension this domain belongs to', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Dimension', verbose_name='dimension'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_description',
            field=models.TextField(blank=True, default='', help_text='Domain description', null=True, verbose_name='domain description'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_title',
            field=models.CharField(error_messages={'unique': 'A domain with that title already exists.'}, help_text='Domain title', max_length=50, unique=True, verbose_name='domain title'),
        ),
        migrations.AlterField(
            model_name='multipletextchoices',
            name='choice_text',
            field=models.TextField(help_text='Choice text', max_length=1000, verbose_name='choice text'),
        ),
        migrations.AlterField(
            model_name='multipletextchoices',
            name='question',
            field=models.ForeignKey(help_text='Question this choice belongs to', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Question', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='domain',
            field=models.ForeignKey(help_text='Domain this question belongs to', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Domain', verbose_name='domain'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(help_text='Question text', max_length=1000, verbose_name='question text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Yes/No Question'), (1, 'Five Weight Scale'), (2, 'Percentage'), (3, 'Multiple Choice')], default=3, help_text='Question type', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='userchoice',
            name='choice',
            field=models.SmallIntegerField(blank=True, help_text='User choice', null=True, verbose_name='choice'),
        ),
        migrations.AlterField(
            model_name='userchoice',
            name='multipleChoice',
            field=models.ForeignKey(help_text='User choice (from multiple)', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.MultipleTextChoices', verbose_name='multiple choice'),
        ),
        migrations.AlterField(
            model_name='userchoice',
            name='question',
            field=models.ForeignKey(help_text='Question this choice belongs to', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Question', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='userchoice',
            name='user',
            field=models.ForeignKey(help_text='User this choice belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default='', help_text='User working address', max_length=200, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='User birth date', null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, default='', help_text='Company this user belongs to', max_length=200, null=True, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, default='', help_text='Department this user belongs to', max_length=200, null=True, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='User display name', max_length=200, null=True, verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='employee_id',
            field=models.IntegerField(blank=True, error_messages={'unique': 'A user with that employee id already exists.'}, help_text='User employee id', null=True, unique=True, verbose_name='employee id'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], help_text='User gender', null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, default='', help_text='User job title', max_length=100, null=True, verbose_name='job title'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notes', max_length=1000, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, default='', help_text='User telephone number', max_length=20, null=True, verbose_name='telephone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='User ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
