# Generated by Django 3.0.2 on 2020-03-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0006_auto_20200218_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimension',
            old_name='dimension_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='dimension',
            old_name='dimension_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='dimension',
            old_name='dimension_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='domain_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='domain_title',
            new_name='title',
        ),
    ]
