# Generated by Django 3.0.2 on 2020-03-12 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('sbam_app', '0006_auto_20200305_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', help_text='Group display name', max_length=200, null=True, verbose_name='display name')),
                ('description', models.CharField(blank=True, default='', help_text='Group description', max_length=200, null=True, verbose_name='description')),
                ('notes', models.TextField(blank=True, default='', help_text='Notes', max_length=1000, null=True, verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this group should be treated as active. Unselect this instead of deleting groups.', verbose_name='active')),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation timestamp')),
                ('creator', models.ForeignKey(blank=True, help_text='Creator User ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('group', models.OneToOneField(help_text='Group ID', on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='group')),
            ],
            options={
                'verbose_name': 'group profile',
                'verbose_name_plural': 'group profiles',
            },
        ),
    ]
