# Generated by Django 3.0.2 on 2020-03-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0007_auto_20200305_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='user_owner',
            new_name='owner',
        ),
    ]
