# Generated by Django 3.0.2 on 2020-03-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0008_auto_20200310_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(default='', help_text='Test title', max_length=100),
            preserve_default=False,
        ),
    ]
