# Generated by Django 3.0.2 on 2020-03-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0009_test_title'),
        ('sbam_app', '0007_groupprofile'),
    ]

    operations = [
    ]
