# Generated by Django 3.0.2 on 2020-03-24 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0010_merge_20200321_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimension',
            options={},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterField(
            model_name='dimension',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Dimension description', null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='title',
            field=models.CharField(help_text='Dimension title', max_length=50),
        ),
        migrations.AlterField(
            model_name='domain',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Domain description', null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='dimension',
            field=models.ForeignKey(help_text='Dimension this domain belongs to', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Dimension'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='title',
            field=models.CharField(help_text='Domain title', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], help_text='User gender', null=True, verbose_name='gender'),
        ),
    ]
