# Generated by Django 3.0.2 on 2020-04-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0011_auto_20200324_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='type',
            field=models.CharField(choices=[('BOOL', 'boolean'), ('PERC10', 'percentage_step_10'), ('PERC20', 'percentage_step_20'), ('AGR5', 'agreement_scale_5_options'), ('CUSTOM_R', 'custom_question')], max_length=23),
        ),
    ]
