# Generated by Django 3.0.2 on 2020-04-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0012_auto_20200407_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='takes_multiple',
            field=models.BooleanField(default=False),
        ),
    ]
