# Generated by Django 3.0.5 on 2020-04-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0012_auto_20200407_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprofile',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='display_name',
        ),
    ]
