# Generated by Django 3.0.2 on 2020-04-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0014_auto_20200413_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='type',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(default='title', help_text='Questionnaire title', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaignquestionanswer',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbam_app.QuestionnaireAssignment'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='level',
            field=models.SmallIntegerField(choices=[('ORGANISATIONAL', 0), ('INDIVIDUAL', 1)], help_text='Dimension level'),
        ),
    ]
