# Generated by Django 3.0.2 on 2020-04-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0014_auto_20200413_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text_el',
            field=models.TextField(help_text="question's text", null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_en',
            field=models.TextField(help_text="question's text", null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_it',
            field=models.TextField(help_text="question's text", null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_ro',
            field=models.TextField(help_text="question's text", null=True),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='text_el',
            field=models.TextField(help_text="question's option text", null=True),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='text_en',
            field=models.TextField(help_text="question's option text", null=True),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='text_it',
            field=models.TextField(help_text="question's option text", null=True),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='text_ro',
            field=models.TextField(help_text="question's option text", null=True),
        ),
    ]
