# Generated by Django 3.0.5 on 2020-04-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0015_auto_20200427_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentresult',
            name='answer_time',
            field=models.DateField(),
        ),
    ]
