# Generated by Django 3.0.2 on 2020-04-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0016_auto_20200427_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionoption',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
