# Generated by Django 3.0.5 on 2020-05-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0016_auto_20200428_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='type',
            field=models.CharField(choices=[('BOOL_P', 'boolean_positive'), ('BOOL_N', 'boolean_negative'), ('PERC10_P', 'percentage_step_10_positive'), ('PERC10_N', 'percentage_step_10_negative'), ('PERC20_P', 'percentage_step_20_positive'), ('PERC20_N', 'percentage_step_20_negative'), ('AGR5_P', 'agreement_scale_5_positive'), ('AGR5_N', 'agreement_scale_5_negative'), ('CUSTOM_R', 'custom_question')], max_length=23),
        ),
    ]
