# Generated by Django 3.0.5 on 2020-05-11 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('sbam_app', '0017_auto_20200502_1157'), ('sbam_app', '0018_auto_20200505_1329'), ('sbam_app', '0019_campaign_title')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sbam_app', '0016_auto_20200428_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='type',
            field=models.CharField(choices=[('BOOL_P', 'boolean_positive'), ('BOOL_N', 'boolean_negative'), ('PERC10_P', 'percentage_step_10_positive'), ('PERC10_N', 'percentage_step_10_negative'), ('PERC20_P', 'percentage_step_20_positive'), ('PERC20_N', 'percentage_step_20_negative'), ('AGR5_P', 'agreement_scale_5_positive'), ('AGR5_N', 'agreement_scale_5_negative'), ('CUSTOM_R', 'custom_question')], max_length=23),
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'assignment', 'verbose_name_plural': 'assignments'},
        ),
        migrations.AlterModelOptions(
            name='assignmentresult',
            options={'verbose_name': 'assignment result', 'verbose_name_plural': 'assignment results'},
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'campaign', 'verbose_name_plural': 'campaigns'},
        ),
        migrations.AlterModelOptions(
            name='campaignquestionanswer',
            options={'verbose_name': 'campaign question answer', 'verbose_name_plural': 'campaign question answers'},
        ),
        migrations.AlterModelOptions(
            name='dimension',
            options={'verbose_name': 'dimension', 'verbose_name_plural': 'dimensions'},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'domain', 'verbose_name_plural': 'domains'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name': 'questionnaire', 'verbose_name_plural': 'questionnaires'},
        ),
        migrations.AlterModelOptions(
            name='questionnaireassignment',
            options={'verbose_name': 'questionnaire assignment', 'verbose_name_plural': 'questionnaire assignments'},
        ),
        migrations.AlterModelOptions(
            name='questionoption',
            options={'verbose_name': 'question option', 'verbose_name_plural': 'question options'},
        ),
        migrations.AlterModelOptions(
            name='questiontype',
            options={'verbose_name': 'question type', 'verbose_name_plural': 'question types'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'test', 'verbose_name_plural': 'tests'},
        ),
        migrations.AlterModelOptions(
            name='testassignment',
            options={'verbose_name': 'test assignment', 'verbose_name_plural': 'test assignments'},
        ),
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.FloatField(default=1, help_text="Multiplier indicating question's significance", verbose_name='weight'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='weight',
            field=models.FloatField(default=1, help_text="Multiplier indicating questionnaire's significance", verbose_name='weight'),
        ),
        migrations.AddField(
            model_name='test',
            name='weight',
            field=models.FloatField(default=1, help_text="Multiplier indicating test's significance", verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='campaign',
            field=models.ForeignKey(help_text='The campaign this assignment derives from', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Campaign', verbose_name='campaign'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Completed'), (2, 'Cancelled')], default=0, help_text='Status of an assignment indicating if it has been completed or not', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(help_text='Assignee', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='assignmentresult',
            name='answer_time',
            field=models.DateField(help_text='The date this assignment result was achieved', verbose_name='answer time'),
        ),
        migrations.AlterField(
            model_name='assignmentresult',
            name='assignment',
            field=models.ForeignKey(help_text='Assignment this result refers to', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Assignment', verbose_name='assignment'),
        ),
        migrations.AlterField(
            model_name='assignmentresult',
            name='score',
            field=models.FloatField(help_text='Achieved assignment score', verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(help_text='Campaign end date', verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(help_text='The user who created the campaign', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(help_text='Campaign start date', verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.IntegerField(choices=[(0, 'Finished'), (1, 'Active'), (2, 'Cancelled')], default=1, help_text='Campaign status', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='campaignquestionanswer',
            name='assignment',
            field=models.ForeignKey(help_text='The assignment this answer belongs to', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.QuestionnaireAssignment', verbose_name='assignment'),
        ),
        migrations.AlterField(
            model_name='campaignquestionanswer',
            name='question',
            field=models.ForeignKey(help_text='The question this answer refers to', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Question', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='campaignquestionanswer',
            name='question_option',
            field=models.ForeignKey(help_text='The option selected by the assignee', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.QuestionOption', verbose_name='question option'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Dimension description', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='level',
            field=models.SmallIntegerField(choices=[(0, 'Organisational'), (1, 'Individual')], help_text='Dimension level', verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='title',
            field=models.CharField(help_text='Dimension title', max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Domain description', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='dimension',
            field=models.ForeignKey(help_text='Dimension this domain belongs to', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Dimension', verbose_name='dimension'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='title',
            field=models.CharField(help_text='Domain title', max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_active',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, help_text='Designates whether this question is being used by a specific questionnaire', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(help_text='Question type', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.QuestionType', verbose_name='question_type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(help_text='The questionnaire this question belongs to', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Questionnaire', verbose_name='questionnaire'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='Question text', verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='domain',
            field=models.ForeignKey(help_text='The domain this questionnaire belongs to', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Domain', verbose_name='domain'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='is_active',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, help_text='Designates whether this questionnaire is being used for the evaluation of a specific domain', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(help_text='Questionnaire title', max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='questionnaireassignment',
            name='questionnaire',
            field=models.ForeignKey(help_text='Questionnaire assigned', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Questionnaire', verbose_name='questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='is_active',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, help_text='Designates whether this question option is being offered by a specific question type', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='question_type',
            field=models.ForeignKey(help_text='Question type this option refers to', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.QuestionType', verbose_name='question type'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='text',
            field=models.TextField(help_text="Question's option text", verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='value',
            field=models.FloatField(help_text='Value corresponding to specific option', verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='takes_multiple',
            field=models.BooleanField(default=False, help_text='Designates if specific question type accepts multiple answers', verbose_name='takes multiple'),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='type',
            field=models.CharField(choices=[('BOOL_P', 'boolean_positive'), ('BOOL_N', 'boolean_negative'), ('PERC10_P', 'percentage_step_10_positive'), ('PERC10_N', 'percentage_step_10_negative'), ('PERC20_P', 'percentage_step_20_positive'), ('PERC20_N', 'percentage_step_20_negative'), ('AGR5_P', 'agreement_scale_5_positive'), ('AGR5_N', 'agreement_scale_5_negative'), ('CUSTOM_R', 'custom_question')], help_text='Question type', max_length=23, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='test',
            name='domain',
            field=models.ForeignKey(help_text='The domain this test belongs to', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Domain', verbose_name='domain'),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_active',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, help_text='Designates whether this test is being used for the evaluation of a specific domain', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(help_text='Test title', max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='testassignment',
            name='test',
            field=models.ForeignKey(help_text='Test assigned', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Test', verbose_name='test'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='title',
            field=models.CharField(default=0, help_text='Campaign title', max_length=20, verbose_name='title'),
            preserve_default=False,
        ),
    ]
