# Generated by Django 3.0.2 on 2020-04-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0017_auto_20200427_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='id_in_questionnaire',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionoption',
            name='id_in_question',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
