# Generated by Django 3.0.5 on 2020-05-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0018_auto_20200505_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='title',
            field=models.CharField(default=0, help_text='Campaign title', max_length=20, verbose_name='title'),
            preserve_default=False,
        ),
    ]
