# Generated by Django 3.0.5 on 2020-05-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0019_auto_20200427_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(help_text='Questionnaire title', max_length=100),
        ),
    ]
