# Generated by Django 3.0.5 on 2020-05-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0020_auto_20200507_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='status',
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Is the campaign cancelled?'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='title',
            field=models.CharField(default='', help_text='Campaign title', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentresult',
            name='answer_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(help_text='Questionnaire title', max_length=200),
        ),
    ]
