# Generated by Django 3.0.5 on 2020-05-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0021_auto_20200509_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentresult',
            name='answer_time',
            field=models.DateField(),
        ),
    ]
