# Generated by Django 3.0.5 on 2020-05-19 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sbam_app', '0023_auto_20200512_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(help_text='Assignee', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireSelfAssessment',
            fields=[
                ('selfassessment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sbam_app.SelfAssessment')),
                ('questionnaire', models.ForeignKey(help_text='Questionnaire assigned', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Questionnaire', verbose_name='questionnaire')),
            ],
            options={
                'verbose_name': 'questionnaire assignment',
                'verbose_name_plural': 'questionnaire assignments',
            },
            bases=('sbam_app.selfassessment',),
        ),
        migrations.CreateModel(
            name='SelfAssessmentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_time', models.DateField(help_text='The date this self assessment survey result was achieved', verbose_name='answer time')),
                ('score', models.FloatField(help_text='Achieved self assessment survey score', verbose_name='score')),
                ('selfassessment', models.ForeignKey(help_text='self assessment survey this result refers to', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.SelfAssessment', verbose_name='self assessment')),
            ],
        ),
        migrations.CreateModel(
            name='TestSelfAssessment',
            fields=[
                ('selfassessment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sbam_app.SelfAssessment')),
                ('test', models.ForeignKey(help_text='Test assigned', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Test', verbose_name='test')),
            ],
            options={
                'verbose_name': 'test assignment',
                'verbose_name_plural': 'test assignments',
            },
            bases=('sbam_app.selfassessment',),
        ),
        migrations.CreateModel(
            name='SelfAssessmentQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(help_text='The question this answer refers to', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Question', verbose_name='question')),
                ('question_option', models.ForeignKey(help_text='The option selected by the assignee', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.QuestionOption', verbose_name='question option')),
                ('selfassessment', models.ForeignKey(help_text='The self assessment survey this answer belongs to', on_delete=django.db.models.deletion.CASCADE, to='sbam_app.QuestionnaireSelfAssessment', verbose_name='assignment')),
            ],
            options={
                'verbose_name': 'self assessment question answer',
                'verbose_name_plural': 'self assessment question answers',
            },
        ),
    ]
