# Generated by Django 3.0.5 on 2020-06-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0024_questionnaireselfassessment_selfassessment_selfassessmentquestionanswer_selfassessmentresult_testsel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(help_text='Campaign title', max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='title',
            field=models.CharField(help_text='Domain title', max_length=100, verbose_name='title'),
        ),
    ]
