# Generated by Django 3.0.2 on 2020-06-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0025_auto_20200603_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentresult',
            name='answer_time',
            field=models.DateTimeField(help_text='The date this assignment result was achieved', verbose_name='answer time'),
        ),
        migrations.AlterField(
            model_name='selfassessmentresult',
            name='answer_time',
            field=models.DateTimeField(help_text='The date this self assessment survey result was achieved', verbose_name='answer time'),
        ),
    ]
