# Generated by Django 3.0.2 on 2020-06-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0026_auto_20200623_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='creation_date',
            field=models.DateField(default='2020-06-25', help_text='Campaign creation date', verbose_name='creation date'),
            preserve_default=False,
        ),
    ]
