# Generated by Django 3.0.5 on 2020-11-17 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0027_campaign_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='dimension',
            field=models.ForeignKey(help_text='Dimension this domain belongs to', on_delete=django.db.models.deletion.PROTECT, to='sbam_app.Dimension', verbose_name='dimension'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(help_text='Question type', on_delete=django.db.models.deletion.PROTECT, to='sbam_app.QuestionType', verbose_name='question_type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(help_text='The questionnaire this question belongs to', on_delete=django.db.models.deletion.PROTECT, to='sbam_app.Questionnaire', verbose_name='questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='domain',
            field=models.ForeignKey(help_text='The domain this questionnaire belongs to', on_delete=django.db.models.deletion.PROTECT, to='sbam_app.Domain', verbose_name='domain'),
        ),
        migrations.AlterField(
            model_name='questionnaireassignment',
            name='questionnaire',
            field=models.ForeignKey(help_text='Questionnaire assigned', on_delete=django.db.models.deletion.PROTECT, to='sbam_app.Questionnaire', verbose_name='questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='question_type',
            field=models.ForeignKey(help_text='Question type this option refers to', on_delete=django.db.models.deletion.PROTECT, to='sbam_app.QuestionType', verbose_name='question type'),
        ),
    ]
