# Generated by Django 3.0.5 on 2020-12-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0028_auto_20201117_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(default='', help_text="Campaign's description", verbose_name='description'),
            preserve_default=False,
        ),
    ]
