# Generated by Django 3.0.5 on 2021-02-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0029_campaign_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mittre_id', models.CharField(max_length=20, unique=True)),
                ('mittre_json_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mitigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mittre_id', models.CharField(max_length=20, unique=True)),
                ('mittre_json_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=100)),
                ('attack_patterns', models.ManyToManyField(to='sbam_app.AttackPattern')),
                ('domains', models.ManyToManyField(to='sbam_app.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveAttackPatterns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbam_app.AttackPattern')),
            ],
        ),
    ]
