# Generated by Django 3.0.5 on 2021-05-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0030_activeattackpatterns_attackpattern_mitigation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text_ro',
            new_name='text_bg',
        ),
        migrations.RenameField(
            model_name='questionoption',
            old_name='text_ro',
            new_name='text_bg',
        ),
    ]
