# Generated by Django 3.0.5 on 2021-03-10 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0030_activeattackpatterns_attackpattern_mitigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsiderThreat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InsiderThreatSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=100)),
                ('insider_threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat', to='sbam_app.InsiderThreat')),
            ],
        ),
        migrations.CreateModel(
            name='InsiderThreatsFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=100)),
                ('domains', models.ManyToManyField(to='sbam_app.Domain')),
                ('insider_threat', models.ManyToManyField(to='sbam_app.InsiderThreat')),
            ],
        ),
    ]
