# Generated by Django 3.0.5 on 2021-05-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0031_auto_20210512_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='description_bg',
            field=models.TextField(blank=True, default='', help_text='Dimension description', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='description_el',
            field=models.TextField(blank=True, default='', help_text='Dimension description', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='description_en',
            field=models.TextField(blank=True, default='', help_text='Dimension description', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='description_it',
            field=models.TextField(blank=True, default='', help_text='Dimension description', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='title_bg',
            field=models.CharField(help_text='Dimension title', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='title_el',
            field=models.CharField(help_text='Dimension title', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='title_en',
            field=models.CharField(help_text='Dimension title', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='title_it',
            field=models.CharField(help_text='Dimension title', max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='domain',
            name='description_bg',
            field=models.TextField(blank=True, default='', help_text='Domain description', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='domain',
            name='description_el',
            field=models.TextField(blank=True, default='', help_text='Domain description', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='domain',
            name='description_en',
            field=models.TextField(blank=True, default='', help_text='Domain description', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='domain',
            name='description_it',
            field=models.TextField(blank=True, default='', help_text='Domain description', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='domain',
            name='title_bg',
            field=models.CharField(help_text='Domain title', max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='domain',
            name='title_el',
            field=models.CharField(help_text='Domain title', max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='domain',
            name='title_en',
            field=models.CharField(help_text='Domain title', max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='domain',
            name='title_it',
            field=models.CharField(help_text='Domain title', max_length=100, null=True, verbose_name='title'),
        ),
    ]
