# Generated by Django 3.0.5 on 2021-05-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0032_activeinsiderthreats'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeattackpatterns',
            name='score',
            field=models.FloatField(default=0.0, help_text='Severity of threat', verbose_name='score'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activeinsiderthreats',
            name='score',
            field=models.FloatField(default=0.0, help_text='Severity of threat', verbose_name='score'),
            preserve_default=False,
        ),
    ]
