# Generated by Django 3.0.5 on 2021-09-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0032_auto_20210524_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='title_bg',
            field=models.CharField(help_text='Questionnaire title', max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='title_el',
            field=models.CharField(help_text='Questionnaire title', max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='title_en',
            field=models.CharField(help_text='Questionnaire title', max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='title_it',
            field=models.CharField(help_text='Questionnaire title', max_length=200, null=True, verbose_name='title'),
        ),
    ]
