# Generated by Django 3.0.5 on 2021-06-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0034_auto_20210520_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='insiderthreatsfactor',
            name='insider_threat_subtype',
            field=models.ManyToManyField(to='sbam_app.InsiderThreatSubType'),
        ),
        migrations.AlterField(
            model_name='assignmentresult',
            name='answer_time',
            field=models.DateField(help_text='The date this assignment result was achieved', verbose_name='answer time'),
        ),
    ]
