# Generated by Django 3.0.5 on 2021-06-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0035_auto_20210628_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfassessmentresult',
            name='answer_time',
            field=models.DateField(help_text='The date this self assessment survey result was achieved', verbose_name='answer time'),
        ),
    ]
