# Generated by Django 3.0.5 on 2021-07-27 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sbam_app', '0036_auto_20210628_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_access', models.CharField(choices=[('all_services', 'Full Access'), ('no_services', 'No Access'), ('organization_report', 'organization report'), ('campaign_report', 'campaign report'), ('user_report', 'user report'), ('group_report', 'group report'), ('get_campaigns', 'get campaigns')], max_length=100)),
                ('user', models.OneToOneField(help_text='User ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
