# Generated by Django 3.0.5 on 2021-09-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0037_userservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='kafkaStatus',
            field=models.CharField(help_text='Kafka status', max_length=10, null=True, verbose_name='kafka status'),
        ),
    ]
