# Generated by Django 3.0.5 on 2021-10-12 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0033_auto_20210927_2252'),
        ('sbam_app', '0038_campaign_kafkastatus'),
    ]

    operations = [
    ]
