# Generated by Django 3.0.5 on 2021-10-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0039_merge_20211012_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_general', models.BooleanField(help_text='Designates if a recommendation is general or insider', verbose_name='general')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000)),
                ('insider_threat', models.ManyToManyField(to='sbam_app.InsiderThreat', verbose_name='recommendation')),
            ],
        ),
    ]
