# Generated by Django 3.0.5 on 2021-10-22 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0040_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveInsiderRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Severity of recommendation', verbose_name='score')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbam_app.Recommendation')),
            ],
        ),
    ]
