# Generated by Django 3.0.5 on 2021-10-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbam_app', '0041_activeinsiderrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeinsiderrecommendation',
            name='threatName',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
